### ISSUE TITLE
Lesson 3 title spelling is wrong

### ISSUE THREAD

**Issue by SzilvasiPeter** [jojoee/chatgpt-prompt-engineering-for-developers#1]
Actual: The l3-iterative-prompt-development.ipynb title is "Iterative Prompt Develelopment"
Expected: Iterative Prompt Development

**Comment by jojoee** [comment]
Thank you for reporting :pray: , fixed https://github.com/jojoee/chatgpt-prompt-engineering-for-developers/commit/01c941cb3796cec5ac77eed2357c01f186f6411f
