### ISSUE TITLE
Lesson 4 review spelling mistakes

### ISSUE THREAD

**Issue by SzilvasiPeter** [jojoee/chatgpt-prompt-engineering-for-developers#2]
There are a couple of spelling errors in the [l4-summarizing.ipynb](https://github.com/jojoee/chatgpt-prompt-engineering-for-developers/blob/master/l4-summarizing.ipynb) notebook.

ecommerce -> e-commerce

- Summarize with a word/sentence/character limit
- Summarize with a focus on shipping and delivery
- Summarize with a focus on price and value
- Try "extract" instead of "summarize"
- Last code cell's prompt text

deparmtment -> department

- Summarize with a focus on shipping and delivery
- Summarize with a focus on price and value

**Comment by jojoee** [comment]
Close due to https://github.com/jojoee/chatgpt-prompt-engineering-for-developers/pull/3
